name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-none-eabi

    - name: Build BlinkingLedAsm
      working-directory: ./BlinkingLedAsm
      run: make all

    - name: Build BlinkingLedC
      working-directory: ./BlinkingLedC
      run: make all
