name: Workflow test

on:
  push:
    paths:
      - '**'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-none-eabi
    - name: Build BlinkingLedAsm
      working-directory: ./BlinkingLedAsm
      run: make all

    - name: Build BlinkingLedC
      working-directory: ./BlinkingLedC
      run: make all
